version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          RAILS_ENV: test
          PGUSER: root

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: balloon_bot_test

    working_directory: ~/balloon-bot
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v $BUNDLER_VERSION

      - restore_cache:
          name: Restore Bundler and Yarn Dependency Cache
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install Bundler Dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - run:
          name: Install Yarn Dependencies
          command: |
            yarn install --frozen-lockfile

      - save_cache:
          name: Save Bundler and Yarn Dependency Cache
          paths:
            - ./web/vendor/bundle
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Database Setup
          command: |
            cd web
            bundle exec rake db:create
            bundle exec rake db:migrate

      # run tests!
      - run:
          name: Run Backend Tests
          command: |
            mkdir /tmp/test-results

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            core web persistence

      - run:
          name: Run Front-end Tests
          command: |
            yarn test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
orbs:
  heroku: circleci/heroku@0.0.8
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
